name: Deploy Backend

on:
  push:
    paths:
      - 'task-manager-backend/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: task-manager-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy SAM Application
        run: |
          sam build
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset \
            --stack-name task-manager-backend \
            --capabilities CAPABILITY_IAM \
            --region $AWS_REGION

